### ISSUE TITLE
[Medium] Illu und UI Feedback einarbeiten

### ISSUE THREAD

**Issue by madlmaedl** [m-m-mic/reactville#21]
MICHI: 
- Landing: text zentrieren, hinterer Flügel weg, evtl. insgesamt größer
- router road: menschen animieren + enge kanten, häuserhöhe achten + Illu nach rechts schieben
- store: auto, menschen animieren+ straße auf höhe wie bürgersteig
- api: menschen animieren

EVI:
- Boilerplate rauszoomen
- Component: häuser gleiche höhe oder stärkerer unterschied + feuertreppe
- Style: zentrieren, Blitzer, größere Abstände?
- API: rauszoomen
- Shared: Straßenbahn + animieren (vorne, hinten)
- result: zeppelin animieren, motel, weiterrauszoomen
- Quickselect: Bahnhof kleiner + türkis, Bahn animieren

**Comment by m-m-mic** [comment]
Morgen review + schließen
