### ISSUE TITLE
[High] Create poster for year end exhibition

### ISSUE THREAD

**Issue by m-m-mic** [m-m-mic/reactville#26]
- Poster DIN A2
 - Completed by: 12.07. via email to Stephan
 - Title, our names, Stephan, project title
 - CMYK
 - PDF X3
 - ISO Coated V3
 - Export once with 3mm bleed and once without

**Comment by madlmaedl** [comment]
Stefans email:
angaben auf dem plakat:
- name des projekts
- namen der studierenden
- name des dozenten (also meiner)
- projektbeschreibung
- evtl. bilder, stills, wie ihr denkt.

deadline für das plakat:
freitag, 12.07.2024
per mail an mich (kein wetransfer)

dateivorgaben:
dateityp: PDF X3
farbraum: ISO coated V3
format: DIN A2

bitte sendet je gruppe 2 versionen: eine mit 3 mm beschnittzugabe, eine ohne
